# Mercadona Order History retreiving
This jupyter notebook is designed to run the functions in the "order_history_retreiving.py" script to scrape order history information from the Mercadona supermarket's website specific to a user.

In [1]:
from order_history_retrieving import get_purchase_history, get_categories_from_scraping, assign_product_codes
import pandas as pd
from dotenv import load_dotenv
import os

### Load dotenv
First we load the zipcode from our .env file. The functions use this information to log in and scrape the site, it can be stored in a variable and used in the function calls.

In [2]:
load_dotenv()

True

In [3]:
mercadona_user = os.getenv("mercadona_user")
mercadona_password = os.getenv("mercadona_password")
postal_code = os.getenv("cod_postal")

In [4]:
orders = get_purchase_history(postal_code, mercadona_user, mercadona_password, headless=False)

Success!

In [5]:
orders

,product,units,price,order_number,fecha
0,Tomate pera,2,0.60,13996475,2023-03-18
1,Hummus de garbanzos Hacendado con pimiento del...,1,1.45,13996475,2023-03-18
2,Acondicionador Repara & Protege Pantene,1,3.80,13996475,2023-03-18
3,Palitos de zanahoria,1,1.78,13996475,2023-03-18
4,Fajitas pollo y verduras,3,11.97,13996475,2023-03-18
...,...,...,...,...,...
650,Pechugas enteras de pollo,1,4.32,12793662,2022-10-06
651,Pechugas enteras de pollo,1,4.40,12793662,2022-10-06
652,Medallones pechuga de pollo marinado,1,4.32,12793662,2022-10-06
653,Aguacates,1,2.90,12793662,2022-10-06
654,Aguacates,1,3.03,12793662,2022-10-06

In [6]:
cat_codes = get_categories_from_scraping('../scraping/scraping_output/Mercadona Scraping 2023-03-11_21-39-33.csv')
cat_codes

/Users/kike/Documents/Personal/Educación/IronHack/Final Project/final_project/mercadona/order_history/order_history_retrieving.py:194: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  cat_codes["product_price_per_unit"] = cat_codes["product_price_per_unit"].str.replace("|","")
/Users/kike/Documents/Personal/Educación/IronHack/Final Project/final_project/mercadona/order_history/order_history_retrieving.py:195: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  cat_codes["product_unit"] = cat_codes["product_unit"].str.replace("/","").str.replace(".","")

,product,product_category,product_subcategory,product_code
0,"Aceite de oliva 0,4º Hacendado","Aceite, especias y salsas","Aceite, vinagre y sal",4241
1,"Aceite de oliva 0,4º Hacendado","Aceite, especias y salsas","Aceite, vinagre y sal",4240
2,Aceite de oliva virgen extra Hacendado,"Aceite, especias y salsas","Aceite, vinagre y sal",4717
3,Aceite de oliva virgen extra Hacendado,"Aceite, especias y salsas","Aceite, vinagre y sal",4740
4,Aceite de oliva virgen extra Hacendado Gran Se...,"Aceite, especias y salsas","Aceite, vinagre y sal",4706
...,...,...,...,...
5224,Bebida de pomelo Hacendado sin azúcares añadidos,Not Available,Compartir,39604
5225,Bebida guayaba Hacendado sin azúcares añadidos,Not Available,Compartir,39659
5226,Bebida de pera Hacendado sin azúcares añadidos,Not Available,Compartir,39628
5227,Zumo de pomelo Hacendado,Not Available,Compartir,39696
5228,Zumo de manzana selección Hacendado,Not Available,Compartir,39922

In [7]:
order_history = assign_product_codes(cat_codes, orders)

In [8]:
order_history

,product,units,price,order_number,fecha,product_code,price_per_unit
0,Tomate pera,2,0.60,13996475,2023-03-18,69912,0.30
1,Hummus de garbanzos Hacendado con pimiento del...,1,1.45,13996475,2023-03-18,80862,1.45
2,Acondicionador Repara & Protege Pantene,1,3.80,13996475,2023-03-18,35615,3.80
3,Palitos de zanahoria,1,1.78,13996475,2023-03-18,69877,1.78
4,Fajitas pollo y verduras,3,11.97,13996475,2023-03-18,4284,3.99
...,...,...,...,...,...,...,...
856,Pechugas enteras de pollo,1,4.40,12793662,2022-10-06,3682,4.40
857,Pechugas enteras de pollo,1,4.40,12793662,2022-10-06,3682,4.40
858,Medallones pechuga de pollo marinado,1,4.32,12793662,2022-10-06,2831,4.32
859,Aguacates,1,2.90,12793662,2022-10-06,3858,2.90
860,Aguacates,1,3.03,12793662,2022-10-06,3858,3.03

In [9]:
order_history.to_csv('outputs/order_history.csv', sep="~")